-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
-- نظام مالي مستقل عن الطلبات والمخزون، مرتبط فقط باسم المخزن للتقارير.

create table if not exists public.finance_accounts (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    name text not null,
    account_type text not null check (account_type in ('cash','bank')),
    opening_balance numeric not null default 0,
    is_active boolean not null default true,
    notes text,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create table if not exists public.finance_transactions (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    account_id bigint not null references public.finance_accounts(id) on delete restrict,
    transaction_type text not null check (transaction_type in ('income','expense','transfer_in','transfer_out','opening')),
    amount numeric not null check (amount > 0),
    transaction_date date not null default current_date,
    reference_type text,
    reference_id bigint,
    counterparty text,
    notes text,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create table if not exists public.finance_expense_categories (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (warehouse, name)
);

create table if not exists public.finance_expenses (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    account_id bigint not null references public.finance_accounts(id) on delete restrict,
    category_id bigint references public.finance_expense_categories(id) on delete set null,
    amount numeric not null check (amount > 0),
    expense_date date not null default current_date,
    payee text,
    notes text,
    attachment_url text,
    transaction_id bigint unique references public.finance_transactions(id) on delete set null,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create table if not exists public.finance_suppliers (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    name text not null,
    phone text,
    email text,
    address text,
    notes text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid(),
    unique (warehouse, name)
);

create table if not exists public.finance_purchase_orders (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    supplier_id bigint not null references public.finance_suppliers(id) on delete restrict,
    status text not null default 'مسودة' check (status in ('مسودة','مستحق','مدفوع جزئيًا','مدفوع','ملغي')),
    total numeric not null default 0,
    paid_amount numeric not null default 0,
    purchase_date date not null default current_date,
    due_date date,
    notes text,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create table if not exists public.finance_supplier_payments (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    purchase_order_id bigint not null references public.finance_purchase_orders(id) on delete cascade,
    account_id bigint not null references public.finance_accounts(id) on delete restrict,
    amount numeric not null check (amount > 0),
    payment_date date not null default current_date,
    notes text,
    transaction_id bigint unique references public.finance_transactions(id) on delete set null,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create table if not exists public.finance_price_lists (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    name text not null,
    price_mode text not null default 'fixed' check (price_mode in ('fixed','percentage')),
    adjustment numeric not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (warehouse, name)
);

create table if not exists public.finance_customer_payments (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    customer_name text not null,
    account_id bigint not null references public.finance_accounts(id) on delete restrict,
    amount numeric not null check (amount > 0),
    payment_date date not null default current_date,
    notes text,
    transaction_id bigint unique references public.finance_transactions(id) on delete set null,
    created_at timestamptz not null default now(),
    created_by uuid default auth.uid()
);

create index if not exists finance_accounts_warehouse_idx on public.finance_accounts(warehouse);
create index if not exists finance_transactions_warehouse_date_idx on public.finance_transactions(warehouse, transaction_date desc);
create index if not exists finance_expenses_warehouse_date_idx on public.finance_expenses(warehouse, expense_date desc);
create index if not exists finance_suppliers_warehouse_idx on public.finance_suppliers(warehouse);
create index if not exists finance_purchase_orders_warehouse_idx on public.finance_purchase_orders(warehouse, purchase_date desc);

alter table public.finance_accounts enable row level security;
alter table public.finance_transactions enable row level security;
alter table public.finance_expense_categories enable row level security;
alter table public.finance_expenses enable row level security;
alter table public.finance_suppliers enable row level security;
alter table public.finance_purchase_orders enable row level security;
alter table public.finance_supplier_payments enable row level security;
alter table public.finance_price_lists enable row level security;
alter table public.finance_customer_payments enable row level security;

-- كل عمليات النظام تمر عبر الدوال أدناه حتى تبقى بياناته منفصلة عن الطلبات والمخزون.
create or replace function public.finance_access(p_warehouse text)
returns boolean language sql stable security definer set search_path = public as $$
    select auth.uid() is not null and public.team_can_access_warehouse(p_warehouse, 'finance');
$$;

create or replace function public.list_finance_dashboard(p_warehouse text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare result jsonb;
begin
    if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية للإدارة المالية'; end if;
    select jsonb_build_object(
        'accounts_balance', coalesce((select sum(a.opening_balance + coalesce((select sum(case when t.transaction_type in ('income','transfer_in','opening') then t.amount else -t.amount end) from public.finance_transactions t where t.account_id=a.id),0)) from public.finance_accounts a where a.warehouse=p_warehouse and a.is_active),0),
        'month_expenses', coalesce((select sum(amount) from public.finance_expenses where warehouse=p_warehouse and date_trunc('month', expense_date)=date_trunc('month', current_date)),0),
        'suppliers_due', coalesce((select sum(greatest(total-paid_amount,0)) from public.finance_purchase_orders where warehouse=p_warehouse and status <> 'ملغي'),0),
        'accounts_count', coalesce((select count(*) from public.finance_accounts where warehouse=p_warehouse and is_active),0)
    ) into result;
    return result;
end;
$$;

create or replace function public.list_finance_accounts(p_warehouse text)
returns table(id bigint,name text,account_type text,opening_balance numeric,current_balance numeric,notes text,is_active boolean)
language sql security definer set search_path = public as $$
 select a.id,a.name,a.account_type,a.opening_balance,
 a.opening_balance + coalesce((select sum(case when t.transaction_type in ('income','transfer_in','opening') then t.amount else -t.amount end) from public.finance_transactions t where t.account_id=a.id),0),a.notes,a.is_active
 from public.finance_accounts a where a.warehouse=p_warehouse and public.finance_access(p_warehouse) order by a.created_at;
$$;

create or replace function public.save_finance_account(p_warehouse text,p_name text,p_type text,p_opening numeric default 0,p_notes text default null)
returns bigint language plpgsql security definer set search_path = public as $$ declare new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 if trim(coalesce(p_name,''))='' then raise exception 'اسم الحساب مطلوب'; end if;
 insert into public.finance_accounts(warehouse,name,account_type,opening_balance,notes) values(p_warehouse,trim(p_name),p_type,coalesce(p_opening,0),nullif(trim(coalesce(p_notes,'')),'')) returning id into new_id; return new_id;
end; $$;

create or replace function public.list_finance_expense_categories(p_warehouse text)
returns table(id bigint,name text) language sql security definer set search_path = public as $$ select id,name from public.finance_expense_categories where warehouse=p_warehouse and is_active and public.finance_access(p_warehouse) order by name; $$;

create or replace function public.save_finance_expense_category(p_warehouse text,p_name text)
returns bigint language plpgsql security definer set search_path = public as $$ declare new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 insert into public.finance_expense_categories(warehouse,name) values(p_warehouse,trim(p_name)) on conflict(warehouse,name) do update set is_active=true returning id into new_id; return new_id;
end; $$;

create or replace function public.list_finance_expenses(p_warehouse text)
returns table(id bigint,expense_date date,category text,account text,payee text,amount numeric,notes text)
language sql security definer set search_path = public as $$
 select e.id,e.expense_date,coalesce(c.name,'غير مصنف'),a.name,e.payee,e.amount,e.notes from public.finance_expenses e join public.finance_accounts a on a.id=e.account_id left join public.finance_expense_categories c on c.id=e.category_id where e.warehouse=p_warehouse and public.finance_access(p_warehouse) order by e.expense_date desc,e.id desc;
$$;

create or replace function public.save_finance_expense(p_warehouse text,p_account_id bigint,p_category_id bigint,p_amount numeric,p_date date,p_payee text default null,p_notes text default null)
returns bigint language plpgsql security definer set search_path = public as $$ declare transaction_id bigint; new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'أدخل مبلغًا صحيحًا'; end if;
 if not exists(select 1 from public.finance_accounts where id=p_account_id and warehouse=p_warehouse and is_active) then raise exception 'الحساب غير صالح'; end if;
 insert into public.finance_transactions(warehouse,account_id,transaction_type,amount,transaction_date,counterparty,notes) values(p_warehouse,p_account_id,'expense',p_amount,coalesce(p_date,current_date),nullif(trim(coalesce(p_payee,'')),''),nullif(trim(coalesce(p_notes,'')),'')) returning id into transaction_id;
 insert into public.finance_expenses(warehouse,account_id,category_id,amount,expense_date,payee,notes,transaction_id) values(p_warehouse,p_account_id,p_category_id,p_amount,coalesce(p_date,current_date),nullif(trim(coalesce(p_payee,'')),''),nullif(trim(coalesce(p_notes,'')),''),transaction_id) returning id into new_id; return new_id;
end; $$;

create or replace function public.list_finance_suppliers(p_warehouse text)
returns table(id bigint,name text,phone text,email text,address text,notes text,due_balance numeric)
language sql security definer set search_path = public as $$
 select s.id,s.name,s.phone,s.email,s.address,s.notes,coalesce((select sum(greatest(p.total-p.paid_amount,0)) from public.finance_purchase_orders p where p.supplier_id=s.id and p.status <> 'ملغي'),0) from public.finance_suppliers s where s.warehouse=p_warehouse and s.is_active and public.finance_access(p_warehouse) order by s.name;
$$;

create or replace function public.save_finance_supplier(p_warehouse text,p_name text,p_phone text default null,p_email text default null,p_address text default null,p_notes text default null)
returns bigint language plpgsql security definer set search_path = public as $$ declare new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 if trim(coalesce(p_name,''))='' then raise exception 'اسم المورد مطلوب'; end if;
 insert into public.finance_suppliers(warehouse,name,phone,email,address,notes) values(p_warehouse,trim(p_name),nullif(trim(coalesce(p_phone,'')),''),nullif(trim(coalesce(p_email,'')),''),nullif(trim(coalesce(p_address,'')),''),nullif(trim(coalesce(p_notes,'')),'')) on conflict(warehouse,name) do update set phone=excluded.phone,email=excluded.email,address=excluded.address,notes=excluded.notes,is_active=true returning id into new_id; return new_id;
end; $$;

grant execute on function public.list_finance_dashboard(text),public.list_finance_accounts(text),public.save_finance_account(text,text,text,numeric,text),public.list_finance_expense_categories(text),public.save_finance_expense_category(text,text),public.list_finance_expenses(text),public.save_finance_expense(text,bigint,bigint,numeric,date,text,text),public.list_finance_suppliers(text),public.save_finance_supplier(text,text,text,text,text,text) to authenticated;

create or replace function public.list_finance_price_lists(p_warehouse text)
returns table(id bigint,name text,price_mode text,adjustment numeric,is_active boolean)
language sql security definer set search_path = public as $$
 select id,name,price_mode,adjustment,is_active from public.finance_price_lists where warehouse=p_warehouse and public.finance_access(p_warehouse) order by name;
$$;

create or replace function public.save_finance_price_list(p_warehouse text,p_name text,p_mode text,p_adjustment numeric)
returns bigint language plpgsql security definer set search_path = public as $$ declare new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 if trim(coalesce(p_name,''))='' then raise exception 'اسم القائمة مطلوب'; end if;
 insert into public.finance_price_lists(warehouse,name,price_mode,adjustment) values(p_warehouse,trim(p_name),p_mode,coalesce(p_adjustment,0)) on conflict(warehouse,name) do update set price_mode=excluded.price_mode,adjustment=excluded.adjustment,is_active=true returning id into new_id; return new_id;
end; $$;

create or replace function public.list_finance_customer_dues(p_warehouse text)
returns table(customer_name text,order_total numeric,paid_amount numeric,due_amount numeric)
language sql security definer set search_path = public as $$
 with sales as (select trim(customer_name) customer_name,coalesce(sum(total),0) total from public.orders where warehouse=p_warehouse and coalesce(status,'') <> 'ملغي' group by trim(customer_name)), payments as (select trim(customer_name) customer_name,coalesce(sum(amount),0) paid from public.finance_customer_payments where warehouse=p_warehouse group by trim(customer_name))
 select s.customer_name,s.total,coalesce(p.paid,0),greatest(s.total-coalesce(p.paid,0),0) from sales s left join payments p on lower(p.customer_name)=lower(s.customer_name) where public.finance_access(p_warehouse) order by greatest(s.total-coalesce(p.paid,0),0) desc;
$$;

create or replace function public.save_finance_customer_payment(p_warehouse text,p_customer_name text,p_account_id bigint,p_amount numeric,p_date date,p_notes text default null)
returns bigint language plpgsql security definer set search_path = public as $$ declare transaction_id bigint; new_id bigint; begin
 if not public.finance_access(p_warehouse) then raise exception 'ليس لديك صلاحية'; end if;
 if trim(coalesce(p_customer_name,''))='' or coalesce(p_amount,0)<=0 then raise exception 'اسم العميل والمبلغ الصحيح مطلوبان'; end if;
 insert into public.finance_transactions(warehouse,account_id,transaction_type,amount,transaction_date,counterparty,notes) values(p_warehouse,p_account_id,'income',p_amount,coalesce(p_date,current_date),trim(p_customer_name),p_notes) returning id into transaction_id;
 insert into public.finance_customer_payments(warehouse,customer_name,account_id,amount,payment_date,notes,transaction_id) values(p_warehouse,trim(p_customer_name),p_account_id,p_amount,coalesce(p_date,current_date),p_notes,transaction_id) returning id into new_id; return new_id;
end; $$;

grant execute on function public.list_finance_price_lists(text),public.save_finance_price_list(text,text,text,numeric),public.list_finance_customer_dues(text),public.save_finance_customer_payment(text,text,bigint,numeric,date,text) to authenticated;
