-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
-- يسجل الأصناف غير المتوفرة من تعديل الطلب، ويُظهر الطلبات ذات حالة «جديد» في الإدارة.

create table if not exists public.order_shortages (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    warehouse text not null,
    order_id bigint not null,
    product_id bigint,
    product_code text,
    category text,
    product_type text,
    type text,
    company text,
    model text,
    color text,
    quantity integer not null default 1,
    price numeric not null default 0,
    image text,
    reported_by uuid default auth.uid()
);

create index if not exists order_shortages_warehouse_created_idx on public.order_shortages (warehouse, created_at desc);
alter table public.order_shortages enable row level security;

create or replace function public.report_order_shortage(p_order_id bigint, p_item jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare selected_order public.orders%rowtype;
begin
  select * into selected_order from public.orders where id = p_order_id;
  if not found then raise exception 'الطلب غير موجود'; end if;
  if not public.team_can_access_warehouse(selected_order.warehouse, 'orders') then raise exception 'ليس لديك صلاحية'; end if;
  insert into public.order_shortages (warehouse,order_id,product_id,product_code,category,product_type,type,company,model,color,quantity,price,image)
  values (selected_order.warehouse,(p_order_id),(p_item->>'product_id')::bigint,p_item->>'product_code',p_item->>'category',p_item->>'product_type',p_item->>'type',p_item->>'company',p_item->>'model',p_item->>'color',greatest(1,coalesce((p_item->>'quantity')::integer,1)),greatest(0,coalesce((p_item->>'price')::numeric,0)),p_item->>'image');
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.list_warehouse_shortages(p_warehouse text)
returns setof public.order_shortages language sql security definer set search_path = public stable as $$
  select * from public.order_shortages where warehouse = p_warehouse and public.team_can_access_warehouse(p_warehouse, 'orders') order by created_at desc;
$$;

-- كان الشرط التالي يخفي أي طلب يعاد إلى «جديد» من صفحة الإدارة.
-- احذفه من دالة list_warehouse_orders الموجودة لديك ثم نفّذ نسخة الدالة المناسبة من ملف fix-team-warehouse-orders-access.sql
-- بعد إزالة السطر: and coalesce(order_row.status, 'جديد') <> 'جديد'

grant execute on function public.report_order_shortage(bigint,jsonb) to authenticated;
grant execute on function public.list_warehouse_shortages(text) to authenticated;
notify pgrst, 'reload schema';
