-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
-- ينشئ سجل العينات المستقل لكل مخزن وصلاحيات إدارته.

create table if not exists public.warehouse_samples (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    warehouse text not null,
    name text not null,
    product_code text,
    quantity integer not null check (quantity > 0),
    recipient text,
    notes text,
    created_by uuid default auth.uid()
);

create index if not exists warehouse_samples_warehouse_created_idx
on public.warehouse_samples (warehouse, created_at desc);

alter table public.warehouse_samples enable row level security;

create or replace function public.list_warehouse_samples(p_warehouse text)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
begin
    if auth.uid() is null or not public.team_can_access_warehouse(p_warehouse, 'products') then
        raise exception 'ليس لديك صلاحية لعرض عينات هذا المخزن';
    end if;

    return coalesce((
        select jsonb_agg(to_jsonb(sample) order by sample.id desc)
        from public.warehouse_samples sample
        where trim(sample.warehouse) = trim(p_warehouse)
    ), '[]'::jsonb);
end;
$$;

create or replace function public.save_warehouse_sample(p_sample jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    saved_sample public.warehouse_samples%rowtype;
    target_warehouse text := trim(coalesce(p_sample->>'warehouse', ''));
    sample_name text := trim(coalesce(p_sample->>'name', ''));
    sample_quantity integer := greatest(0, coalesce((p_sample->>'quantity')::integer, 0));
begin
    if auth.uid() is null or not public.team_can_access_warehouse(target_warehouse, 'products') then
        raise exception 'ليس لديك صلاحية لإضافة عينات لهذا المخزن';
    end if;
    if sample_name = '' then raise exception 'اسم العينة مطلوب'; end if;
    if sample_quantity <= 0 then raise exception 'كمية العينة يجب أن تكون أكبر من صفر'; end if;

    insert into public.warehouse_samples (warehouse, name, product_code, quantity, recipient, notes)
    values (
        target_warehouse,
        sample_name,
        nullif(trim(coalesce(p_sample->>'product_code', '')), ''),
        sample_quantity,
        nullif(trim(coalesce(p_sample->>'recipient', '')), ''),
        nullif(trim(coalesce(p_sample->>'notes', '')), '')
    )
    returning * into saved_sample;

    return to_jsonb(saved_sample);
end;
$$;

create or replace function public.delete_warehouse_sample(p_sample_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    target_warehouse text;
begin
    select warehouse into target_warehouse
    from public.warehouse_samples
    where id = p_sample_id;

    if not found then raise exception 'العينة غير موجودة'; end if;
    if auth.uid() is null or not public.team_can_access_warehouse(target_warehouse, 'products') then
        raise exception 'ليس لديك صلاحية لحذف هذه العينة';
    end if;

    delete from public.warehouse_samples where id = p_sample_id;
end;
$$;

grant execute on function public.list_warehouse_samples(text) to authenticated;
grant execute on function public.save_warehouse_sample(jsonb) to authenticated;
grant execute on function public.delete_warehouse_sample(bigint) to authenticated;
notify pgrst, 'reload schema';
