-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
-- ينشئ سجل مرتجعات مستقلًا؛ لا يحذف عناصر الفاتورة الأصلية ويعيد كمية المرتجع إلى مخزن الفاتورة.

create table if not exists public.order_returns (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    warehouse text not null,
    order_id bigint not null references public.orders(id) on delete restrict,
    customer_name text,
    customer_phone text,
    status text not null default 'مسجل',
    total numeric not null default 0,
    notes text,
    inventory_restocked_at timestamptz,
    created_by uuid default auth.uid()
);

alter table public.order_returns
add column if not exists inventory_restocked_at timestamptz;

create table if not exists public.order_return_items (
    id bigint generated by default as identity primary key,
    return_id bigint not null references public.order_returns(id) on delete cascade,
    order_item_id bigint not null,
    product_id bigint,
    product_code text,
    category text,
    product_type text,
    type text,
    company text,
    model text,
    color text,
    quantity integer not null check (quantity > 0),
    price numeric not null default 0,
    image text
);

create index if not exists order_returns_warehouse_created_idx on public.order_returns (warehouse, created_at desc);
create index if not exists order_return_items_order_item_idx on public.order_return_items (order_item_id);

alter table public.order_returns enable row level security;
alter table public.order_return_items enable row level security;

create or replace function public.create_order_return(
    p_order_id bigint,
    p_items jsonb,
    p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    source_order public.orders%rowtype;
    source_item public.order_items%rowtype;
    requested_item jsonb;
    requested_quantity integer;
    already_returned integer;
    new_return_id bigint;
    return_total numeric := 0;
begin
    select * into source_order from public.orders where id = p_order_id for update;
    if not found then raise exception 'الفاتورة غير موجودة'; end if;
    if auth.uid() is null or not public.team_can_access_warehouse(source_order.warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية لتسجيل مرتجع لهذا المخزن';
    end if;
    if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'حدد منتجًا واحدًا على الأقل للمرتجع';
    end if;

    -- نتحقق أولاً من كل الكميات قبل إنشاء سجل المرتجع.
    for requested_item in select value from jsonb_array_elements(p_items) loop
        requested_quantity := greatest(0, coalesce((requested_item->>'quantity')::integer, 0));
        if requested_quantity <= 0 then raise exception 'كمية المرتجع يجب أن تكون أكبر من صفر'; end if;
        select * into source_item
        from public.order_items
        where id = (requested_item->>'order_item_id')::bigint and order_id = p_order_id;
        if not found then raise exception 'أحد منتجات المرتجع لا ينتمي إلى هذه الفاتورة'; end if;

        select coalesce(sum(return_item.quantity), 0) into already_returned
        from public.order_return_items return_item
        join public.order_returns return_doc on return_doc.id = return_item.return_id
        where return_item.order_item_id = source_item.id
          and return_doc.status <> 'ملغي';
        if requested_quantity > greatest(0, source_item.quantity - already_returned) then
            raise exception 'كمية المرتجع تتجاوز الكمية المتاحة للمنتج %', coalesce(source_item.product_code, source_item.id::text);
        end if;
    end loop;

    insert into public.order_returns (warehouse, order_id, customer_name, customer_phone, notes)
    values (source_order.warehouse, source_order.id, source_order.customer_name, source_order.customer_phone, nullif(trim(coalesce(p_notes, '')), ''))
    returning id into new_return_id;

    for requested_item in select value from jsonb_array_elements(p_items) loop
        requested_quantity := (requested_item->>'quantity')::integer;
        select * into source_item
        from public.order_items
        where id = (requested_item->>'order_item_id')::bigint and order_id = p_order_id;

        insert into public.order_return_items (
            return_id, order_item_id, product_id, product_code, category, product_type,
            type, company, model, color, quantity, price, image
        ) values (
            new_return_id, source_item.id, source_item.product_id, source_item.product_code,
            source_item.category, source_item.product_type, source_item.type, source_item.company,
            source_item.model, source_item.color, requested_quantity, source_item.price, source_item.image
        );
        -- لا نعدّل الفاتورة أو عناصرها، بل نرجع كمية المرتجع إلى نسخة المنتج
        -- التابعة لمخزن الفاتورة نفسه.
        update public.products
        set quantity = coalesce(quantity, 0) + requested_quantity
        where id = source_item.product_id
          and trim(warehouse) = trim(source_order.warehouse);
        if not found then
            raise exception 'تعذر إعادة كمية المنتج % إلى مخزن الفاتورة', coalesce(source_item.product_code, source_item.id::text);
        end if;
        return_total := return_total + (requested_quantity * coalesce(source_item.price, 0));
    end loop;

    update public.order_returns
    set total = return_total, inventory_restocked_at = now()
    where id = new_return_id;
    return jsonb_build_object('id', new_return_id, 'total', return_total, 'status', 'مسجل', 'inventory_restocked', true);
end;
$$;

create or replace function public.list_warehouse_returns(p_warehouse text)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
begin
    if auth.uid() is null or not public.team_can_access_warehouse(p_warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية لعرض مرتجعات هذا المخزن';
    end if;
    return coalesce((
        select jsonb_agg(
            to_jsonb(return_doc) || jsonb_build_object(
                'items', coalesce((
                    select jsonb_agg(to_jsonb(return_item) order by return_item.id)
                    from public.order_return_items return_item
                    where return_item.return_id = return_doc.id
                ), '[]'::jsonb)
            ) order by return_doc.id desc
        )
        from public.order_returns return_doc
        where trim(return_doc.warehouse) = trim(p_warehouse)
    ), '[]'::jsonb);
end;
$$;

grant execute on function public.create_order_return(bigint, jsonb, text) to authenticated;
grant execute on function public.list_warehouse_returns(text) to authenticated;
notify pgrst, 'reload schema';
