-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
-- مرتجعات يدوية مستقلة: لا تنشئ طلباً ولا تعدّل أي تحضير موجود.

create table if not exists public.manual_warehouse_returns (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    warehouse text not null,
    customer_name text not null,
    customer_phone text,
    total numeric not null default 0,
    notes text,
    status text not null default 'مسجل',
    created_by uuid default auth.uid()
);

create table if not exists public.manual_warehouse_return_items (
    id bigint generated by default as identity primary key,
    return_id bigint not null references public.manual_warehouse_returns(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    product_code text not null,
    category text,
    product_type text,
    type text,
    company text,
    model text,
    color text,
    storage_location text,
    quantity integer not null check (quantity > 0),
    price numeric not null default 0
);

create index if not exists manual_warehouse_returns_warehouse_created_idx
on public.manual_warehouse_returns (warehouse, created_at desc);
create index if not exists manual_warehouse_return_items_return_idx
on public.manual_warehouse_return_items (return_id);

alter table public.manual_warehouse_returns enable row level security;
alter table public.manual_warehouse_return_items enable row level security;

create or replace function public.create_manual_warehouse_return(p_return jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    target_warehouse text := trim(coalesce(p_return->>'warehouse', ''));
    selected_customer text := trim(coalesce(p_return->>'customer_name', ''));
    selected_phone text := nullif(trim(coalesce(p_return->>'customer_phone', '')), '');
    requested_item jsonb;
    requested_quantity integer;
    requested_document_quantity integer;
    requested_price numeric;
    prepared_quantity integer;
    already_returned_quantity integer;
    matched_product public.products%rowtype;
    new_return_id bigint;
    return_total numeric := 0;
begin
    if auth.uid() is null or not public.team_can_access_warehouse(target_warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية لتسجيل مرتجع لهذا المخزن';
    end if;
    if selected_customer = '' then raise exception 'اسم العميل مطلوب'; end if;
    if not exists (
        select 1 from public.orders order_doc
        where trim(order_doc.warehouse) = target_warehouse
          and lower(trim(coalesce(order_doc.customer_name, ''))) = lower(selected_customer)
          and coalesce(order_doc.status, '') <> 'ملغي'
    ) then
        raise exception 'اختر عميلاً مسجلاً في صفحة العملاء';
    end if;
    if jsonb_typeof(p_return->'items') <> 'array' or jsonb_array_length(p_return->'items') = 0 then
        raise exception 'أضف منتجاً واحداً على الأقل';
    end if;

    -- نفحص كل المنتجات قبل الحفظ حتى لا يُسجّل مرتجع ناقص.
    for requested_item in select value from jsonb_array_elements(p_return->'items') loop
        requested_quantity := greatest(0, coalesce((requested_item->>'quantity')::integer, 0));
        if trim(coalesce(requested_item->>'product_code', '')) = '' or requested_quantity <= 0 then
            raise exception 'رقم المنتج والكمية الصحيحة مطلوبان لكل صف';
        end if;
        select * into matched_product from public.products product_row
        where trim(product_row.warehouse) = target_warehouse
          and trim(coalesce(product_row.product_code, '')) = trim(requested_item->>'product_code')
          and lower(trim(coalesce(product_row.model, ''))) = lower(trim(coalesce(requested_item->>'model', '')))
          and lower(trim(coalesce(product_row.color, ''))) = lower(trim(coalesce(requested_item->>'color', '')))
        order by product_row.id
        limit 1 for update;
        if not found then
            raise exception 'لم نجد الصنف المطابق للكود % والموديل واللون في هذا المخزن', requested_item->>'product_code';
        end if;
        select coalesce(sum(order_item.quantity), 0)::integer into prepared_quantity
        from public.orders order_doc
        join public.order_items order_item on order_item.order_id = order_doc.id
        where trim(order_doc.warehouse) = target_warehouse
          and lower(trim(coalesce(order_doc.customer_name, ''))) = lower(selected_customer)
          and coalesce(order_doc.status, '') <> 'ملغي'
          and trim(coalesce(order_item.product_code, '')) = trim(requested_item->>'product_code')
          and lower(trim(coalesce(order_item.model, ''))) = lower(trim(coalesce(requested_item->>'model', '')))
          and lower(trim(coalesce(order_item.color, ''))) = lower(trim(coalesce(requested_item->>'color', '')));
        if prepared_quantity <= 0 then
            raise exception 'هذا المنتج غير موجود ضمن تحضيرات العميل المحدد';
        end if;

        select coalesce(sum(return_item.quantity), 0)::integer into already_returned_quantity
        from public.manual_warehouse_return_items return_item
        join public.manual_warehouse_returns return_doc on return_doc.id = return_item.return_id
        where trim(return_doc.warehouse) = target_warehouse
          and lower(trim(coalesce(return_doc.customer_name, ''))) = lower(selected_customer)
          and coalesce(return_doc.status, '') <> 'ملغي'
          and trim(coalesce(return_item.product_code, '')) = trim(requested_item->>'product_code')
          and lower(trim(coalesce(return_item.model, ''))) = lower(trim(coalesce(requested_item->>'model', '')))
          and lower(trim(coalesce(return_item.color, ''))) = lower(trim(coalesce(requested_item->>'color', '')));

        select coalesce(sum(greatest(0, coalesce((candidate.value->>'quantity')::integer, 0))), 0)::integer
        into requested_document_quantity
        from jsonb_array_elements(p_return->'items') candidate(value)
        where trim(coalesce(candidate.value->>'product_code', '')) = trim(requested_item->>'product_code')
          and lower(trim(coalesce(candidate.value->>'model', ''))) = lower(trim(coalesce(requested_item->>'model', '')))
          and lower(trim(coalesce(candidate.value->>'color', ''))) = lower(trim(coalesce(requested_item->>'color', '')));
        if requested_document_quantity > greatest(0, prepared_quantity - already_returned_quantity) then
            raise exception 'كمية المرتجع تتجاوز الكمية المتاحة في التحضير (% قطعة)', greatest(0, prepared_quantity - already_returned_quantity);
        end if;
    end loop;

    insert into public.manual_warehouse_returns (warehouse, customer_name, customer_phone, notes)
    values (target_warehouse, selected_customer, selected_phone, nullif(trim(coalesce(p_return->>'notes', '')), ''))
    returning id into new_return_id;

    for requested_item in select value from jsonb_array_elements(p_return->'items') loop
        requested_quantity := (requested_item->>'quantity')::integer;
        requested_price := greatest(0, coalesce((requested_item->>'price')::numeric, 0));
        select * into matched_product from public.products product_row
        where trim(product_row.warehouse) = target_warehouse
          and trim(coalesce(product_row.product_code, '')) = trim(requested_item->>'product_code')
          and lower(trim(coalesce(product_row.model, ''))) = lower(trim(coalesce(requested_item->>'model', '')))
          and lower(trim(coalesce(product_row.color, ''))) = lower(trim(coalesce(requested_item->>'color', '')))
        order by product_row.id
        limit 1 for update;

        insert into public.manual_warehouse_return_items (
            return_id, product_id, product_code, category, product_type, type, company,
            model, color, storage_location, quantity, price
        ) values (
            new_return_id, matched_product.id, matched_product.product_code,
            coalesce(nullif(trim(requested_item->>'category'), ''), matched_product.category),
            coalesce(nullif(trim(requested_item->>'product_type'), ''), matched_product.product_type),
            coalesce(nullif(trim(requested_item->>'type'), ''), matched_product.type),
            coalesce(nullif(trim(requested_item->>'company'), ''), matched_product.company),
            matched_product.model, matched_product.color,
            coalesce(nullif(trim(requested_item->>'storage_location'), ''), matched_product.storage_location),
            requested_quantity, requested_price
        );
        update public.products
        set quantity = coalesce(quantity, 0) + requested_quantity
        where id = matched_product.id;
        return_total := return_total + (requested_quantity * requested_price);
    end loop;

    update public.manual_warehouse_returns set total = return_total where id = new_return_id;
    return jsonb_build_object('id', new_return_id, 'total', return_total, 'status', 'مسجل');
end;
$$;

create or replace function public.list_warehouse_manual_returns(p_warehouse text)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
begin
    if auth.uid() is null or not public.team_can_access_warehouse(p_warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية لعرض مرتجعات هذا المخزن';
    end if;
    return coalesce((
        select jsonb_agg(
            to_jsonb(return_doc) || jsonb_build_object(
                'items', coalesce((
                    select jsonb_agg(to_jsonb(return_item) order by return_item.id)
                    from public.manual_warehouse_return_items return_item
                    where return_item.return_id = return_doc.id
                ), '[]'::jsonb),
                'manual_return', true
            ) order by return_doc.id desc
        )
        from public.manual_warehouse_returns return_doc
        where trim(return_doc.warehouse) = trim(p_warehouse)
    ), '[]'::jsonb);
end;
$$;

grant execute on function public.create_manual_warehouse_return(jsonb) to authenticated;
grant execute on function public.list_warehouse_manual_returns(text) to authenticated;
notify pgrst, 'reload schema';
