-- صفحة طلبات الشراء: تنشئ طلبًا من النواقص المحددة فقط، ولا تضيف كميات إلى المخزون.

create table if not exists public.purchase_orders (
    id bigint generated by default as identity primary key,
    warehouse text not null,
    status text not null default 'جديد' check (status in ('جديد', 'تم الطلب', 'تم الاستلام', 'ملغي')),
    notes text,
    created_by uuid default auth.uid(),
    created_at timestamptz not null default now()
);

create table if not exists public.purchase_order_items (
    id bigint generated by default as identity primary key,
    purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
    product_code text,
    category text,
    product_type text,
    type text,
    company text,
    model text,
    color text,
    quantity integer not null check (quantity > 0),
    price numeric not null default 0,
    image text,
    shortage_ids jsonb not null default '[]'::jsonb
);

alter table public.order_shortages add column if not exists purchase_order_id bigint references public.purchase_orders(id);
create index if not exists purchase_orders_warehouse_created_idx on public.purchase_orders(warehouse, created_at desc);
create index if not exists purchase_order_items_order_idx on public.purchase_order_items(purchase_order_id);
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create or replace function public.create_purchase_order_from_shortages(p_warehouse text, p_shortage_ids bigint[], p_notes text default null)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_purchase_order_id bigint;
    selected_count integer;
begin
    if auth.uid() is null or not public.team_can_access_warehouse(p_warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية إنشاء طلب شراء لهذا المخزن';
    end if;
    select count(*) into selected_count
    from public.order_shortages
    where id = any(p_shortage_ids) and warehouse = p_warehouse and coalesce(status, 'جديد') = 'جديد';
    if selected_count = 0 then
        raise exception 'لا توجد نواقص جديدة صالحة لإضافتها إلى طلب الشراء';
    end if;

    insert into public.purchase_orders(warehouse, notes, created_by)
    values (p_warehouse, nullif(trim(coalesce(p_notes, '')), ''), auth.uid())
    returning id into new_purchase_order_id;

    insert into public.purchase_order_items(purchase_order_id, product_code, category, product_type, type, company, model, color, quantity, price, image, shortage_ids)
    select new_purchase_order_id, product_code, category, product_type, type, company, model, color,
           sum(greatest(1, quantity))::integer, coalesce(avg(price), 0), max(image), jsonb_agg(id order by id)
    from public.order_shortages
    where id = any(p_shortage_ids) and warehouse = p_warehouse and coalesce(status, 'جديد') = 'جديد'
    group by product_code, category, product_type, type, company, model, color;

    update public.order_shortages
    set status = 'طلب شراء', purchase_order_id = new_purchase_order_id, requested_at = now()
    where id = any(p_shortage_ids) and warehouse = p_warehouse and coalesce(status, 'جديد') = 'جديد';

    return new_purchase_order_id;
end;
$$;

create or replace function public.list_warehouse_purchase_orders(p_warehouse text)
returns table(id bigint, warehouse text, status text, notes text, created_at timestamptz, items jsonb)
language sql
security definer
set search_path = public
stable
as $$
    select purchase.id, purchase.warehouse, purchase.status, purchase.notes, purchase.created_at,
           coalesce(jsonb_agg(jsonb_build_object(
               'id', item.id, 'product_code', item.product_code, 'category', item.category,
               'product_type', item.product_type, 'type', item.type, 'company', item.company,
               'model', item.model, 'color', item.color, 'quantity', item.quantity,
               'price', item.price, 'image', item.image
           ) order by item.id) filter (where item.id is not null), '[]'::jsonb) as items
    from public.purchase_orders purchase
    left join public.purchase_order_items item on item.purchase_order_id = purchase.id
    where purchase.warehouse = p_warehouse and public.team_can_access_warehouse(p_warehouse, 'orders')
    group by purchase.id
    order by purchase.id desc;
$$;

create or replace function public.update_purchase_order(p_purchase_order_id bigint, p_status text, p_notes text, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    purchase public.purchase_orders%rowtype;
    edited_item jsonb;
begin
    select * into purchase from public.purchase_orders where id = p_purchase_order_id;
    if not found then raise exception 'طلب الشراء غير موجود'; end if;
    if auth.uid() is null or not public.team_can_access_warehouse(purchase.warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية تعديل طلب الشراء';
    end if;
    if trim(coalesce(p_status, '')) not in ('جديد', 'تم الطلب', 'تم الاستلام', 'ملغي') then
        raise exception 'حالة طلب الشراء غير صالحة';
    end if;

    update public.purchase_orders
    set status = trim(p_status), notes = nullif(trim(coalesce(p_notes, '')), '')
    where id = p_purchase_order_id;

    for edited_item in select value from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
    loop
        update public.purchase_order_items
        set quantity = greatest(1, coalesce((edited_item->>'quantity')::integer, quantity)),
            price = greatest(0, coalesce((edited_item->>'price')::numeric, price))
        where id = coalesce((edited_item->>'id')::bigint, 0)
          and purchase_order_id = p_purchase_order_id;
    end loop;
end;
$$;

grant execute on function public.create_purchase_order_from_shortages(text, bigint[], text) to authenticated;
grant execute on function public.list_warehouse_purchase_orders(text) to authenticated;
grant execute on function public.update_purchase_order(bigint, text, text, jsonb) to authenticated;

-- إنشاء طلب شراء يدويًا من منتجات المخزن، دون تغيير كميات المخزون.
create or replace function public.create_manual_purchase_order(p_warehouse text, p_items jsonb, p_notes text default null)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_purchase_order_id bigint;
    item jsonb;
    item_count integer;
begin
    if auth.uid() is null or not public.team_can_access_warehouse(p_warehouse, 'orders') then
        raise exception 'ليس لديك صلاحية إنشاء طلب شراء لهذا المخزن';
    end if;
    if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then
        raise exception 'بيانات أصناف طلب الشراء غير صالحة';
    end if;
    select count(*) into item_count from jsonb_array_elements(p_items);
    if item_count = 0 then
        raise exception 'أضف صنفًا واحدًا على الأقل إلى طلب الشراء';
    end if;

    insert into public.purchase_orders(warehouse, notes, created_by)
    values (p_warehouse, nullif(trim(coalesce(p_notes, '')), ''), auth.uid())
    returning id into new_purchase_order_id;

    for item in select value from jsonb_array_elements(p_items)
    loop
        if greatest(0, coalesce((item->>'quantity')::integer, 0)) < 1 then
            raise exception 'كمية صنف طلب الشراء يجب أن تكون أكبر من صفر';
        end if;
        insert into public.purchase_order_items(
            purchase_order_id, product_code, category, product_type, type, company, model, color, quantity, price, image, shortage_ids
        ) values (
            new_purchase_order_id,
            nullif(trim(coalesce(item->>'product_code', '')), ''),
            nullif(trim(coalesce(item->>'category', '')), ''),
            nullif(trim(coalesce(item->>'product_type', '')), ''),
            nullif(trim(coalesce(item->>'type', '')), ''),
            nullif(trim(coalesce(item->>'company', '')), ''),
            nullif(trim(coalesce(item->>'model', '')), ''),
            nullif(trim(coalesce(item->>'color', '')), ''),
            greatest(1, coalesce((item->>'quantity')::integer, 1)),
            greatest(0, coalesce((item->>'price')::numeric, 0)),
            nullif(trim(coalesce(item->>'image', '')), ''),
            '[]'::jsonb
        );
    end loop;
    return new_purchase_order_id;
end;
$$;

grant execute on function public.create_manual_purchase_order(text, jsonb, text) to authenticated;
notify pgrst, 'reload schema';
