-- شغّل هذا الملف وحده في Supabase SQL Editor لإصلاح خطأ 400 في قسم الحسابات والصلاحيات.

create table if not exists public.team_accounts (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'viewer' check (role in ('owner', 'warehouse_manager', 'orders_staff', 'viewer')),
    permissions jsonb not null default '{"warehouses": [], "sections": []}'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid references auth.users(id)
);

create table if not exists public.team_account_audit (
    id bigint generated by default as identity primary key,
    actor_id uuid references auth.users(id),
    target_user_id uuid references auth.users(id),
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

insert into public.team_accounts(user_id, role, permissions, is_active)
select id, 'owner', '{"warehouses": [], "sections": ["dashboard", "products", "orders", "transfers", "accounts"]}'::jsonb, true
from public.admins
on conflict (user_id) do nothing;

create or replace function public.list_team_accounts()
returns table(user_id uuid, email text, role text, permissions jsonb, is_active boolean, created_at timestamptz)
language sql
security definer
set search_path = public, auth
as $$
    select team.user_id, users.email::text, team.role, team.permissions, team.is_active, team.created_at
    from public.team_accounts team
    join auth.users users on users.id = team.user_id
    where exists (select 1 from public.admins admin where admin.id = auth.uid())
    order by team.created_at desc;
$$;

create or replace function public.list_team_account_audit()
returns table(action text, target_email text, created_at timestamptz)
language sql
security definer
set search_path = public, auth
as $$
    select audit.action, users.email::text, audit.created_at
    from public.team_account_audit audit
    left join auth.users users on users.id = audit.target_user_id
    where exists (select 1 from public.admins admin where admin.id = auth.uid())
    order by audit.id desc
    limit 50;
$$;

create or replace function public.get_my_team_access()
returns jsonb
language sql
security definer
set search_path = public
as $$
    select coalesce(
        (select jsonb_build_object('is_active', team.is_active, 'role', team.role, 'permissions', team.permissions)
         from public.team_accounts team where team.user_id = auth.uid()),
        jsonb_build_object('is_active', false, 'role', null, 'permissions', '{}'::jsonb)
    );
$$;

create or replace function public.save_team_account(p_email text, p_role text, p_permissions jsonb)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare target_id uuid;
begin
    if not exists (select 1 from public.admins where id = auth.uid()) then raise exception 'غير مصرح لك بتعديل الصلاحيات'; end if;
    if p_role not in ('owner', 'warehouse_manager', 'orders_staff', 'viewer') then raise exception 'الدور المختار غير صالح'; end if;
    select id into target_id from auth.users where lower(email) = lower(trim(p_email)) limit 1;
    if target_id is null then raise exception 'لا يوجد حساب مسجل بهذا البريد'; end if;
    insert into public.team_accounts(user_id, role, permissions, is_active, updated_by)
    values (target_id, p_role, jsonb_build_object('warehouses', coalesce(p_permissions->'warehouses', '[]'::jsonb), 'sections', coalesce(p_permissions->'sections', '[]'::jsonb)), true, auth.uid())
    on conflict (user_id) do update set role = excluded.role, permissions = excluded.permissions, is_active = true, updated_at = now(), updated_by = auth.uid();
    insert into public.admins(id) values(target_id) on conflict do nothing;
    insert into public.team_account_audit(actor_id, target_user_id, action, details) values(auth.uid(), target_id, 'حفظ صلاحيات الحساب', jsonb_build_object('role', p_role));
end;
$$;

create or replace function public.toggle_team_account(p_user_id uuid, p_is_active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from public.admins where id = auth.uid()) then raise exception 'غير مصرح لك بتعديل الحسابات'; end if;
    if p_user_id = auth.uid() and not p_is_active then raise exception 'لا يمكنك إيقاف حسابك الحالي'; end if;
    update public.team_accounts set is_active = p_is_active, updated_at = now(), updated_by = auth.uid() where user_id = p_user_id;
    if not found then raise exception 'الحساب غير موجود'; end if;
    insert into public.team_account_audit(actor_id, target_user_id, action, details) values(auth.uid(), p_user_id, case when p_is_active then 'تفعيل الحساب' else 'إيقاف الحساب' end, jsonb_build_object('is_active', p_is_active));
end;
$$;

grant execute on function public.list_team_accounts() to authenticated;
grant execute on function public.list_team_account_audit() to authenticated;
grant execute on function public.get_my_team_access() to authenticated;
grant execute on function public.save_team_account(text, text, jsonb) to authenticated;
grant execute on function public.toggle_team_account(uuid, boolean) to authenticated;

notify pgrst, 'reload schema';
