-- شغّل هذا الملف مرة واحدة من Supabase SQL Editor.
-- يصبح كل سجل منتج تابعاً لمخزن واحد، وتكون كميته هي كمية ذلك المخزن.

alter table public.products
add column if not exists warehouse text;

update public.products
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.products
alter column warehouse set default 'الرياض';

alter table public.products
alter column warehouse set not null;

alter table public.products
drop constraint if exists products_warehouse_check;

-- لا نضع قيدًا ثابتًا هنا؛ المخازن تُدار من جدول warehouses لاحقًا.

create index if not exists products_warehouse_idx
on public.products (warehouse);

-- يحفظ أصل نسخة جدة المقابلة لمنتج الرياض، ويُستخدم في التحويلات بين المخزنين.
alter table public.products
add column if not exists copied_from_product_id bigint;

create unique index if not exists products_jeddah_copied_from_unique_idx
on public.products (warehouse, copied_from_product_id)
where copied_from_product_id is not null;

alter table public.orders
add column if not exists warehouse text;

update public.orders
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.orders
alter column warehouse set default 'الرياض';

alter table public.orders
alter column warehouse set not null;

alter table public.orders
drop constraint if exists orders_warehouse_check;

-- لا نضع قيدًا ثابتًا هنا؛ المخازن تُدار من جدول warehouses لاحقًا.

create index if not exists orders_warehouse_idx
on public.orders (warehouse);

alter table public.drivers
add column if not exists warehouse text;

update public.drivers
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.drivers
alter column warehouse set default 'الرياض';

alter table public.drivers
alter column warehouse set not null;

alter table public.drivers
drop constraint if exists drivers_warehouse_check;

-- لا نضع قيدًا ثابتًا هنا؛ المخازن تُدار من جدول warehouses لاحقًا.

create index if not exists drivers_warehouse_idx
on public.drivers (warehouse);

-- ربط مندوب بمخزن وتحديث طلباته، مع تجاوز RLS فقط للأدمن المعتمد.
create or replace function public.assign_driver_warehouse(
    p_driver_number text,
    p_warehouse text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_driver public.drivers%rowtype;
    updated_orders integer;
begin
    if auth.uid() is null or not exists (
        select 1 from public.admins where id = auth.uid()
    ) then
        raise exception 'غير مصرح لك بتغيير مخزن المندوب';
    end if;

    if p_warehouse not in ('الرياض', 'جدة') then
        raise exception 'المخزن المختار غير صالح';
    end if;

    select * into selected_driver
    from public.drivers
    where driver_number::text = trim(p_driver_number)
    limit 1;

    if not found then
        raise exception 'رقم المندوب غير موجود';
    end if;

    update public.drivers
    set warehouse = p_warehouse
    where id = selected_driver.id;

    update public.orders
    set warehouse = p_warehouse
    where driver_number::text = trim(p_driver_number);

    get diagnostics updated_orders = row_count;

    return jsonb_build_object(
        'driver_name', selected_driver.name,
        'warehouse', p_warehouse,
        'orders_updated', updated_orders
    );
end;
$$;

grant execute on function public.assign_driver_warehouse(text, text) to authenticated;

-- =========================================================
-- نظام تحويلات المخزون بين الرياض وجدة
-- =========================================================
create table if not exists public.warehouse_transfers (
    id bigint generated by default as identity primary key,
    source_warehouse text not null check (source_warehouse in ('الرياض', 'جدة')),
    destination_warehouse text not null check (destination_warehouse in ('الرياض', 'جدة')),
    status text not null default 'draft' check (status in ('draft', 'in_transit', 'received', 'cancelled')),
    notes text,
    created_by uuid references auth.users(id),
    created_at timestamptz not null default now(),
    dispatched_at timestamptz,
    received_at timestamptz,
    cancelled_at timestamptz,
    check (source_warehouse <> destination_warehouse)
);

alter table public.warehouse_transfers
add column if not exists requested_by_warehouse text;
alter table public.warehouse_transfers
add column if not exists requested_at timestamptz;
alter table public.warehouse_transfers
drop constraint if exists warehouse_transfers_status_check;
alter table public.warehouse_transfers
add constraint warehouse_transfers_status_check
check (status in ('requested', 'draft', 'in_transit', 'received', 'cancelled'));

create table if not exists public.warehouse_transfer_items (
    id bigint generated by default as identity primary key,
    transfer_id bigint not null references public.warehouse_transfers(id) on delete cascade,
    source_product_id bigint not null references public.products(id),
    destination_product_id bigint not null references public.products(id),
    product_name text not null,
    quantity integer not null check (quantity > 0)
);

alter table public.warehouse_transfer_items add column if not exists product_code text;
alter table public.warehouse_transfer_items add column if not exists company text;
alter table public.warehouse_transfer_items add column if not exists model text;
alter table public.warehouse_transfer_items add column if not exists color text;
alter table public.warehouse_transfer_items add column if not exists product_type text;
alter table public.warehouse_transfer_items add column if not exists type text;
alter table public.warehouse_transfer_items add column if not exists image text;
alter table public.warehouse_transfer_items add column if not exists price numeric;

update public.warehouse_transfer_items transfer_item
set image = product.image,
    price = product.price,
    product_code = coalesce(transfer_item.product_code, product.product_code),
    company = coalesce(transfer_item.company, product.company),
    model = coalesce(transfer_item.model, product.model),
    color = coalesce(transfer_item.color, product.color),
    product_type = coalesce(transfer_item.product_type, product.product_type),
    type = coalesce(transfer_item.type, product.type)
from public.products product
where product.id = transfer_item.source_product_id
  and (transfer_item.image is null or transfer_item.price is null);

create index if not exists warehouse_transfers_created_at_idx on public.warehouse_transfers(created_at desc);
create index if not exists warehouse_transfer_items_transfer_idx on public.warehouse_transfer_items(transfer_id);

alter table public.warehouse_transfers enable row level security;
alter table public.warehouse_transfer_items enable row level security;

drop policy if exists warehouse_transfers_admin_select on public.warehouse_transfers;
create policy warehouse_transfers_admin_select on public.warehouse_transfers
for select to authenticated
using (exists (select 1 from public.admins where id = auth.uid()));

drop policy if exists warehouse_transfer_items_admin_select on public.warehouse_transfer_items;
create policy warehouse_transfer_items_admin_select on public.warehouse_transfer_items
for select to authenticated
using (exists (select 1 from public.admins where id = auth.uid()));

drop function if exists public.create_warehouse_transfer(text, text, text, jsonb);

create or replace function public.create_warehouse_transfer(
    p_source_warehouse text,
    p_destination_warehouse text,
    p_notes text,
    p_items jsonb,
    p_creation_mode text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_transfer_id bigint;
    item jsonb;
    source_product public.products%rowtype;
    destination_product_id bigint;
    requested_quantity integer;
    product_label text;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بإنشاء تحويلات';
    end if;
    if p_source_warehouse not in ('الرياض', 'جدة') or p_destination_warehouse not in ('الرياض', 'جدة') or p_source_warehouse = p_destination_warehouse then
        raise exception 'بيانات المخازن غير صالحة';
    end if;
    if p_creation_mode not in ('request', 'send') then
        raise exception 'نوع التحويل غير صالح';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'أضف منتجاً واحداً على الأقل للتحويل';
    end if;

    insert into public.warehouse_transfers(source_warehouse, destination_warehouse, notes, created_by, status, requested_by_warehouse, requested_at)
    values (
        p_source_warehouse,
        p_destination_warehouse,
        nullif(trim(p_notes), ''),
        auth.uid(),
        case when p_creation_mode = 'request' then 'requested' else 'draft' end,
        case when p_creation_mode = 'request' then p_destination_warehouse else null end,
        case when p_creation_mode = 'request' then now() else null end
    )
    returning id into new_transfer_id;

    for item in select * from jsonb_array_elements(p_items)
    loop
        requested_quantity := (item->>'quantity')::integer;
        if requested_quantity is null or requested_quantity < 1 then
            raise exception 'كمية التحويل يجب أن تكون أكبر من صفر';
        end if;

        select * into source_product
        from public.products
        where id = (item->>'product_id')::bigint
          and warehouse = p_source_warehouse;
        if not found then
            raise exception 'أحد منتجات التحويل غير موجود في المخزن المصدر';
        end if;

        if source_product.quantity < requested_quantity then
            raise exception 'الكمية المطلوبة لمنتج % أكبر من المتاح', coalesce(source_product.model, source_product.product_code, source_product.id::text);
        end if;

        if p_source_warehouse = 'الرياض' then
            select id into destination_product_id
            from public.products
            where warehouse = 'جدة' and copied_from_product_id = source_product.id
            limit 1;
        else
            destination_product_id := source_product.copied_from_product_id;
            if destination_product_id is not null and not exists (
                select 1 from public.products where id = destination_product_id and warehouse = 'الرياض'
            ) then
                destination_product_id := null;
            end if;
        end if;

        if destination_product_id is null then
            raise exception 'لا توجد نسخة مطابقة للمنتج % في مخزن الوجهة. شغّل ملف نسخ منتجات الرياض إلى جدة أولاً.', coalesce(source_product.model, source_product.product_code, source_product.id::text);
        end if;

        product_label := trim(concat_ws(' ', source_product.company, source_product.model, source_product.product_code));
        insert into public.warehouse_transfer_items(
            transfer_id, source_product_id, destination_product_id, product_name, quantity,
            product_code, company, model, color, product_type, type
        ) values (
            new_transfer_id, source_product.id, destination_product_id,
            coalesce(nullif(product_label, ''), 'منتج #' || source_product.id), requested_quantity,
            source_product.product_code, source_product.company, source_product.model,
            source_product.color, source_product.product_type, source_product.type
        );
    end loop;

    return new_transfer_id;
end;
$$;

create or replace function public.process_warehouse_transfer(p_transfer_id bigint, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_transfer public.warehouse_transfers%rowtype;
    transfer_item public.warehouse_transfer_items%rowtype;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بإدارة التحويلات';
    end if;
    select * into selected_transfer from public.warehouse_transfers where id = p_transfer_id for update;
    if not found then raise exception 'التحويل غير موجود'; end if;

    if p_action = 'dispatch' then
        if selected_transfer.status not in ('draft', 'requested') then raise exception 'يمكن شحن المسودات أو طلبات البضاعة المعلقة فقط'; end if;
        for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
            update public.products set quantity = quantity - transfer_item.quantity
            where id = transfer_item.source_product_id and warehouse = selected_transfer.source_warehouse and quantity >= transfer_item.quantity;
            if not found then raise exception 'الكمية لم تعد كافية للمنتج %', transfer_item.product_name; end if;
        end loop;
        update public.warehouse_transfers set status = 'in_transit', dispatched_at = now() where id = p_transfer_id;
    elsif p_action = 'receive' then
        if selected_transfer.status <> 'in_transit' then raise exception 'يمكن استلام التحويلات قيد النقل فقط'; end if;
        for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
            update public.products set quantity = quantity + transfer_item.quantity
            where id = transfer_item.destination_product_id and warehouse = selected_transfer.destination_warehouse;
            if not found then raise exception 'المنتج الوجهة غير موجود للمنتج %', transfer_item.product_name; end if;
        end loop;
        update public.warehouse_transfers set status = 'received', received_at = now() where id = p_transfer_id;
    elsif p_action = 'cancel' then
        if selected_transfer.status = 'received' or selected_transfer.status = 'cancelled' then raise exception 'لا يمكن إلغاء هذا التحويل'; end if;
        if selected_transfer.status = 'in_transit' then
            for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
                update public.products set quantity = quantity + transfer_item.quantity where id = transfer_item.source_product_id;
            end loop;
        end if;
        update public.warehouse_transfers set status = 'cancelled', cancelled_at = now() where id = p_transfer_id;
    else
        raise exception 'إجراء التحويل غير صالح';
    end if;
end;
$$;

grant execute on function public.create_warehouse_transfer(text, text, text, jsonb, text) to authenticated;
grant execute on function public.process_warehouse_transfer(bigint, text) to authenticated;

-- =========================================================
-- إدارة مخازن قابلة للإضافة
-- =========================================================
create table if not exists public.warehouses (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now(),
    created_by uuid references auth.users(id)
);

insert into public.warehouses(name)
values ('الرياض'), ('جدة')
on conflict (name) do nothing;

alter table public.products add column if not exists inventory_key bigint;
update public.products set inventory_key = coalesce(inventory_key, copied_from_product_id, id);
alter table public.products alter column inventory_key set not null;
create index if not exists products_warehouse_inventory_key_idx on public.products(warehouse, inventory_key);

create or replace function public.set_product_inventory_key()
returns trigger language plpgsql as $$
begin
    if new.inventory_key is null then new.inventory_key := new.id; end if;
    return new;
end;
$$;
drop trigger if exists products_set_inventory_key on public.products;
create trigger products_set_inventory_key
before insert on public.products
for each row execute function public.set_product_inventory_key();

alter table public.products drop constraint if exists products_warehouse_check;
alter table public.orders drop constraint if exists orders_warehouse_check;
alter table public.drivers drop constraint if exists drivers_warehouse_check;
alter table public.warehouse_transfers drop constraint if exists warehouse_transfers_source_warehouse_check;
alter table public.warehouse_transfers drop constraint if exists warehouse_transfers_destination_warehouse_check;

alter table public.warehouses enable row level security;
drop policy if exists warehouses_authenticated_select on public.warehouses;
create policy warehouses_authenticated_select on public.warehouses
for select to authenticated using (true);

create or replace function public.add_warehouse(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    new_warehouse public.warehouses%rowtype;
    reference_warehouse text;
    insert_columns text;
    select_columns text;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بإضافة مخزن';
    end if;
    p_name := trim(p_name);
    if p_name is null or length(p_name) < 2 then raise exception 'اسم المخزن يجب أن يحتوي حرفين على الأقل'; end if;
    if length(p_name) > 60 then raise exception 'اسم المخزن طويل جدًا'; end if;

    insert into public.warehouses(name, created_by)
    values (p_name, auth.uid())
    returning * into new_warehouse;

    select name into reference_warehouse from public.warehouses where name <> p_name order by id limit 1;
    if reference_warehouse is not null then
        select
            string_agg(format('%I', column_name), ', ' order by ordinal_position),
            string_agg(case when column_name = 'quantity' then '0' else format('p.%I', column_name) end, ', ' order by ordinal_position)
        into insert_columns, select_columns
        from information_schema.columns
        where table_schema = 'public' and table_name = 'products'
          and column_name not in ('id', 'warehouse', 'copied_from_product_id', 'inventory_key')
          and is_generated = 'NEVER' and is_identity = 'NO';

        execute format(
            'insert into public.products (%s, warehouse, copied_from_product_id, inventory_key)
             select %s, $1, null, p.inventory_key
             from public.products p where p.warehouse = $2',
            insert_columns, select_columns
        ) using p_name, reference_warehouse;
    end if;

    return jsonb_build_object('id', new_warehouse.id, 'name', new_warehouse.name);
end;
$$;

-- تعيد هذه النسخة تعريف التحويلات بحيث تعمل مع أي مخزن جديد.
create or replace function public.create_warehouse_transfer(
    p_source_warehouse text,
    p_destination_warehouse text,
    p_notes text,
    p_items jsonb,
    p_creation_mode text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_transfer_id bigint;
    item jsonb;
    source_product public.products%rowtype;
    destination_product_id bigint;
    requested_quantity integer;
    product_label text;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then raise exception 'غير مصرح لك بإنشاء تحويلات'; end if;
    if not exists (select 1 from public.warehouses where name = p_source_warehouse) or not exists (select 1 from public.warehouses where name = p_destination_warehouse) or p_source_warehouse = p_destination_warehouse then raise exception 'بيانات المخازن غير صالحة'; end if;
    if p_creation_mode not in ('request', 'send') then raise exception 'نوع التحويل غير صالح'; end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'أضف منتجاً واحداً على الأقل للتحويل'; end if;

    insert into public.warehouse_transfers(source_warehouse, destination_warehouse, notes, created_by, status, requested_by_warehouse, requested_at)
    values (p_source_warehouse, p_destination_warehouse, nullif(trim(p_notes), ''), auth.uid(), case when p_creation_mode = 'request' then 'requested' else 'draft' end, case when p_creation_mode = 'request' then p_destination_warehouse else null end, case when p_creation_mode = 'request' then now() else null end)
    returning id into new_transfer_id;

    for item in select * from jsonb_array_elements(p_items) loop
        requested_quantity := (item->>'quantity')::integer;
        if requested_quantity is null or requested_quantity < 1 then raise exception 'كمية التحويل يجب أن تكون أكبر من صفر'; end if;
        select * into source_product from public.products where id = (item->>'product_id')::bigint and warehouse = p_source_warehouse;
        if not found then raise exception 'أحد منتجات التحويل غير موجود في المخزن المصدر'; end if;
        if source_product.quantity < requested_quantity then raise exception 'الكمية المطلوبة لمنتج % أكبر من المتاح', coalesce(source_product.model, source_product.product_code, source_product.id::text); end if;
        select id into destination_product_id from public.products where warehouse = p_destination_warehouse and inventory_key = source_product.inventory_key limit 1;
        if destination_product_id is null then raise exception 'لا توجد نسخة مطابقة للمنتج % في المخزن الوجهة', coalesce(source_product.model, source_product.product_code, source_product.id::text); end if;
        product_label := trim(concat_ws(' ', source_product.company, source_product.model, source_product.product_code));
        insert into public.warehouse_transfer_items(transfer_id, source_product_id, destination_product_id, product_name, quantity, product_code, company, model, color, product_type, type, image, price)
        values (new_transfer_id, source_product.id, destination_product_id, coalesce(nullif(product_label, ''), 'منتج #' || source_product.id), requested_quantity, source_product.product_code, source_product.company, source_product.model, source_product.color, source_product.product_type, source_product.type, source_product.image, source_product.price);
    end loop;
    return new_transfer_id;
end;
$$;

grant execute on function public.add_warehouse(text) to authenticated;

-- ربط المندوب بأي مخزن موجود، وليس بالرياض أو جدة فقط.
create or replace function public.assign_driver_warehouse(
    p_driver_number text,
    p_warehouse text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_driver public.drivers%rowtype;
    updated_orders integer;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بتغيير مخزن المندوب';
    end if;
    if not exists (select 1 from public.warehouses where name = trim(p_warehouse)) then
        raise exception 'المخزن المختار غير موجود';
    end if;

    select * into selected_driver
    from public.drivers
    where driver_number::text = trim(p_driver_number)
    limit 1;
    if not found then raise exception 'رقم المندوب غير موجود'; end if;

    update public.drivers set warehouse = trim(p_warehouse) where id = selected_driver.id;
    update public.orders set warehouse = trim(p_warehouse) where driver_number::text = trim(p_driver_number);
    get diagnostics updated_orders = row_count;

    return jsonb_build_object('driver_name', selected_driver.name, 'warehouse', trim(p_warehouse), 'orders_updated', updated_orders);
end;
$$;
