-- شغّل هذا الملف مرة واحدة من Supabase SQL Editor.
-- يصبح كل سجل منتج تابعاً لمخزن واحد، وتكون كميته هي كمية ذلك المخزن.

alter table public.products
add column if not exists warehouse text;

update public.products
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.products
alter column warehouse set default 'الرياض';

alter table public.products
alter column warehouse set not null;

alter table public.products
drop constraint if exists products_warehouse_check;

alter table public.products
add constraint products_warehouse_check
check (warehouse in ('الرياض', 'جدة'));

create index if not exists products_warehouse_idx
on public.products (warehouse);

-- يحفظ أصل نسخة جدة المقابلة لمنتج الرياض، ويُستخدم في التحويلات بين المخزنين.
alter table public.products
add column if not exists copied_from_product_id bigint;

create unique index if not exists products_jeddah_copied_from_unique_idx
on public.products (warehouse, copied_from_product_id)
where copied_from_product_id is not null;

alter table public.orders
add column if not exists warehouse text;

update public.orders
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.orders
alter column warehouse set default 'الرياض';

alter table public.orders
alter column warehouse set not null;

alter table public.orders
drop constraint if exists orders_warehouse_check;

alter table public.orders
add constraint orders_warehouse_check
check (warehouse in ('الرياض', 'جدة'));

create index if not exists orders_warehouse_idx
on public.orders (warehouse);

alter table public.drivers
add column if not exists warehouse text;

update public.drivers
set warehouse = 'الرياض'
where warehouse is null or btrim(warehouse) = '';

alter table public.drivers
alter column warehouse set default 'الرياض';

alter table public.drivers
alter column warehouse set not null;

alter table public.drivers
drop constraint if exists drivers_warehouse_check;

alter table public.drivers
add constraint drivers_warehouse_check
check (warehouse in ('الرياض', 'جدة'));

create index if not exists drivers_warehouse_idx
on public.drivers (warehouse);

-- ربط مندوب بمخزن وتحديث طلباته، مع تجاوز RLS فقط للأدمن المعتمد.
create or replace function public.assign_driver_warehouse(
    p_driver_number text,
    p_warehouse text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_driver public.drivers%rowtype;
    updated_orders integer;
begin
    if auth.uid() is null or not exists (
        select 1 from public.admins where id = auth.uid()
    ) then
        raise exception 'غير مصرح لك بتغيير مخزن المندوب';
    end if;

    if p_warehouse not in ('الرياض', 'جدة') then
        raise exception 'المخزن المختار غير صالح';
    end if;

    select * into selected_driver
    from public.drivers
    where driver_number::text = trim(p_driver_number)
    limit 1;

    if not found then
        raise exception 'رقم المندوب غير موجود';
    end if;

    update public.drivers
    set warehouse = p_warehouse
    where id = selected_driver.id;

    update public.orders
    set warehouse = p_warehouse
    where driver_number::text = trim(p_driver_number);

    get diagnostics updated_orders = row_count;

    return jsonb_build_object(
        'driver_name', selected_driver.name,
        'warehouse', p_warehouse,
        'orders_updated', updated_orders
    );
end;
$$;

grant execute on function public.assign_driver_warehouse(text, text) to authenticated;

-- =========================================================
-- نظام تحويلات المخزون بين الرياض وجدة
-- =========================================================
create table if not exists public.warehouse_transfers (
    id bigint generated by default as identity primary key,
    source_warehouse text not null check (source_warehouse in ('الرياض', 'جدة')),
    destination_warehouse text not null check (destination_warehouse in ('الرياض', 'جدة')),
    status text not null default 'draft' check (status in ('draft', 'in_transit', 'received', 'cancelled')),
    notes text,
    created_by uuid references auth.users(id),
    created_at timestamptz not null default now(),
    dispatched_at timestamptz,
    received_at timestamptz,
    cancelled_at timestamptz,
    check (source_warehouse <> destination_warehouse)
);

create table if not exists public.warehouse_transfer_items (
    id bigint generated by default as identity primary key,
    transfer_id bigint not null references public.warehouse_transfers(id) on delete cascade,
    source_product_id bigint not null references public.products(id),
    destination_product_id bigint not null references public.products(id),
    product_name text not null,
    quantity integer not null check (quantity > 0)
);

create index if not exists warehouse_transfers_created_at_idx on public.warehouse_transfers(created_at desc);
create index if not exists warehouse_transfer_items_transfer_idx on public.warehouse_transfer_items(transfer_id);

alter table public.warehouse_transfers enable row level security;
alter table public.warehouse_transfer_items enable row level security;

drop policy if exists warehouse_transfers_admin_select on public.warehouse_transfers;
create policy warehouse_transfers_admin_select on public.warehouse_transfers
for select to authenticated
using (exists (select 1 from public.admins where id = auth.uid()));

drop policy if exists warehouse_transfer_items_admin_select on public.warehouse_transfer_items;
create policy warehouse_transfer_items_admin_select on public.warehouse_transfer_items
for select to authenticated
using (exists (select 1 from public.admins where id = auth.uid()));

create or replace function public.create_warehouse_transfer(
    p_source_warehouse text,
    p_destination_warehouse text,
    p_notes text,
    p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_transfer_id bigint;
    item jsonb;
    source_product public.products%rowtype;
    destination_product_id bigint;
    requested_quantity integer;
    product_label text;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بإنشاء تحويلات';
    end if;
    if p_source_warehouse not in ('الرياض', 'جدة') or p_destination_warehouse not in ('الرياض', 'جدة') or p_source_warehouse = p_destination_warehouse then
        raise exception 'بيانات المخازن غير صالحة';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'أضف منتجاً واحداً على الأقل للتحويل';
    end if;

    insert into public.warehouse_transfers(source_warehouse, destination_warehouse, notes, created_by)
    values (p_source_warehouse, p_destination_warehouse, nullif(trim(p_notes), ''), auth.uid())
    returning id into new_transfer_id;

    for item in select * from jsonb_array_elements(p_items)
    loop
        requested_quantity := (item->>'quantity')::integer;
        if requested_quantity is null or requested_quantity < 1 then
            raise exception 'كمية التحويل يجب أن تكون أكبر من صفر';
        end if;

        select * into source_product
        from public.products
        where id = (item->>'product_id')::bigint
          and warehouse = p_source_warehouse;
        if not found then
            raise exception 'أحد منتجات التحويل غير موجود في المخزن المصدر';
        end if;

        if source_product.quantity < requested_quantity then
            raise exception 'الكمية المطلوبة لمنتج % أكبر من المتاح', coalesce(source_product.model, source_product.product_code, source_product.id::text);
        end if;

        if p_source_warehouse = 'الرياض' then
            select id into destination_product_id
            from public.products
            where warehouse = 'جدة' and copied_from_product_id = source_product.id
            limit 1;
        else
            destination_product_id := source_product.copied_from_product_id;
            if destination_product_id is not null and not exists (
                select 1 from public.products where id = destination_product_id and warehouse = 'الرياض'
            ) then
                destination_product_id := null;
            end if;
        end if;

        if destination_product_id is null then
            raise exception 'لا توجد نسخة مطابقة للمنتج % في مخزن الوجهة. شغّل ملف نسخ منتجات الرياض إلى جدة أولاً.', coalesce(source_product.model, source_product.product_code, source_product.id::text);
        end if;

        product_label := trim(concat_ws(' ', source_product.company, source_product.model, source_product.product_code));
        insert into public.warehouse_transfer_items(transfer_id, source_product_id, destination_product_id, product_name, quantity)
        values (new_transfer_id, source_product.id, destination_product_id, coalesce(nullif(product_label, ''), 'منتج #' || source_product.id), requested_quantity);
    end loop;

    return new_transfer_id;
end;
$$;

create or replace function public.process_warehouse_transfer(p_transfer_id bigint, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_transfer public.warehouse_transfers%rowtype;
    transfer_item public.warehouse_transfer_items%rowtype;
begin
    if auth.uid() is null or not exists (select 1 from public.admins where id = auth.uid()) then
        raise exception 'غير مصرح لك بإدارة التحويلات';
    end if;
    select * into selected_transfer from public.warehouse_transfers where id = p_transfer_id for update;
    if not found then raise exception 'التحويل غير موجود'; end if;

    if p_action = 'dispatch' then
        if selected_transfer.status <> 'draft' then raise exception 'يمكن شحن التحويلات المسودة فقط'; end if;
        for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
            update public.products set quantity = quantity - transfer_item.quantity
            where id = transfer_item.source_product_id and warehouse = selected_transfer.source_warehouse and quantity >= transfer_item.quantity;
            if not found then raise exception 'الكمية لم تعد كافية للمنتج %', transfer_item.product_name; end if;
        end loop;
        update public.warehouse_transfers set status = 'in_transit', dispatched_at = now() where id = p_transfer_id;
    elsif p_action = 'receive' then
        if selected_transfer.status <> 'in_transit' then raise exception 'يمكن استلام التحويلات قيد النقل فقط'; end if;
        for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
            update public.products set quantity = quantity + transfer_item.quantity
            where id = transfer_item.destination_product_id and warehouse = selected_transfer.destination_warehouse;
            if not found then raise exception 'المنتج الوجهة غير موجود للمنتج %', transfer_item.product_name; end if;
        end loop;
        update public.warehouse_transfers set status = 'received', received_at = now() where id = p_transfer_id;
    elsif p_action = 'cancel' then
        if selected_transfer.status = 'received' or selected_transfer.status = 'cancelled' then raise exception 'لا يمكن إلغاء هذا التحويل'; end if;
        if selected_transfer.status = 'in_transit' then
            for transfer_item in select * from public.warehouse_transfer_items where transfer_id = p_transfer_id loop
                update public.products set quantity = quantity + transfer_item.quantity where id = transfer_item.source_product_id;
            end loop;
        end if;
        update public.warehouse_transfers set status = 'cancelled', cancelled_at = now() where id = p_transfer_id;
    else
        raise exception 'إجراء التحويل غير صالح';
    end if;
end;
$$;

grant execute on function public.create_warehouse_transfer(text, text, text, jsonb) to authenticated;
grant execute on function public.process_warehouse_transfer(bigint, text) to authenticated;
